ALTER TYPE "PlaceCategory" ADD VALUE IF NOT EXISTS 'AIRBNB';
ALTER TYPE "PlaceCategory" ADD VALUE IF NOT EXISTS 'MIRADOR';

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "pushTokens" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "Place"
ADD COLUMN IF NOT EXISTS "openingHours" TEXT NOT NULL DEFAULT 'Consulta el horario antes de visitar.',
ADD COLUMN IF NOT EXISTS "recommendations" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
